name: infinite_data
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase
  firebase_core: "^0.6.0"
  firebase_auth: "^0.19.0+1"
  cloud_firestore: "^0.15.0"
  
  simple_animations: ^2.2.3
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0
  
  #Routes
  auto_route: ^0.2.1

  #Object comparism instead of == and hashCode
  equatable: ^1.2.3

  page_transition: ^1.1.7+6

  flushbar: ^1.5.0

  event_bus: ^1.1.1

  url_launcher: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.2.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/img1.svg
    - assets/images/img2.png
